spring:
  datasource:
    url: jdbc:h2:mem:junlog;NON_KEYWORDS=USER
#    url: jdbc:postgresql://localhost:5432/junlog
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    defer-datasource-initialization: true
  #    driver-class-name: org.postgresql.Driver
#  sql:
#    init:
#      mode: always

  h2:
    console:
      enabled: true
      path: /h2-console

  data:
    web:
      pageable:
        max-page-size: 2000
        default-page-size: 20
        one-indexed-parameters: true

juna:
  jwt-key: "m1B9hOwtI8AyZ8QTqkOQVcufEcXNGbFdjGNNFBEjQ6A="